name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar el acceso SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-3-95-218-56.compute-1.amazonaws.com >> ~/.ssh/known_hosts

      # Desplegar el código en la instancia EC2
      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@ec2-3-95-218-56.compute-1.amazonaws.com << 'EOF'
            cd /home/ubuntu/practice1.js
            git pull origin main
            # Matar procesos que usen el puerto 3000
            sudo kill -9 $(sudo lsof -t -i:3000) || true
            # Instalar dependencias y reiniciar el servidor
            npm install
            npm start
          EOF
